project:
  type: website
  output-dir: docs

website:
  title: "Talula Wilmot"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: field-experiences.qmd
        text: Field Experiences
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

