project:
  type: website
  output-dir: docs

website:
  title: "Talula Wilmot"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: Experience.qmd
        text: Field Experiences 
      - href: Resume.qmd
        text: Resume

format:
  html:
    theme:
      - morph
    css: style.css
    toc: true
    page-layout: full

editor: visual

